### ISSUE TITLE
Proposal to refactor the directory structure of the app

### ISSUE THREAD

**Issue by hadique** [tanium/SplunkforTanium#1]
Hi, James.

I'd like to refactor the directory structure of the code in this repo to provide a better fit into Splunk's recommended directory structure. See the link below for more details.

http://docs.splunk.com/Documentation/Splunk/latest/AdvancedDev/ShareYourWork

I'd also like to add some field extractions and other Splunk-specific content to the app, but I'll submit that activity as a different issue.

**Comment by JCobeyTanium** [comment]
Thank you for the refact doc. I'll work on the changes.
