### ISSUE TITLE
How do I get "Splunk saved_questions.xml" written in "Tanium Splunk Application 6.5.pdf" page 3?

### ISSUE THREAD

**Issue by KenichiSuda** [tanium/SplunkforTanium#3]
Hello,

I cannot find "Splunk saved_questions.xml" file in this repo, even though the document "Tanium Splunk Application 6.5.pdf" describes it in page 3.
Could you share it with me or tell me how I can get it?

Best Regards,

Kenichi Suda (suda@macnica.net)

**Comment by jzuena** [comment]
I ended up asking our Tanium support engineer, and he had me create the questions manually.

[Splunk Saved Questions.pdf](https://github.com/tanium/SplunkforTanium/files/330674/Splunk.Saved.Questions.pdf)

**Comment by JCobeyTanium** [comment]
Its better to ask the questions and save them by hand since the xml will overwrite the sensors. I'm working now to have a script in this app auto-populate Tanium with the saved questions.

**Comment by KenichiSuda** [comment]
Than you for your information, @jzuena and @JCobeyTanium.
I will try to add the questions manually.
@JCobeyTanium when your script is ready, could you share it?

**Comment by JCobeyTanium** [comment]
Sure thing
