### ISSUE TITLE
Cannot get right answers with "Get Index Query File Details[*, notepad.exe, *, *, *, *, *, 10] from all machines" question.

### ISSUE THREAD

**Issue by KenichiSuda** [tanium/SplunkforTanium#5]
When I try the following search query on Splunk with Tanium app, I get only "[no results]" in each field.

` | taniumnlp --question "Get Index Query File Details[*, notepad.exe, *, *, *, *, *, 10] from all machines" --timeout 20`

I doubt that "tanium_nlp.py" cannot handle "sensor parameters".

Thank you.

**Comment by JCobeyTanium** [comment]
The earlier versions of Tanium could do this properly. Now the NLP via the api strips out the parms and a few other things (like where clauses). Im going to remove the NLP option altogether from future releases.
