### ISSUE TITLE
Escaping Quotes in Question via Splunk

### ISSUE THREAD

**Issue by BoriBori** [tanium/SplunkforTanium#9]
For those trying to run commands like the one below, you must escape the quotes by using the escape character found in the w3 reference below.

Example: | taniumnlp --timeout "60" --question "Get Run Keys from all machines with Computer Name containing &quot;<Computer Name to Search>&quot;"

Reference:
https://www.w3.org/TR/xml11/#syntax 

The documentation online currently is only for the splunkbase app not the one you can download from the Github repository.

Also, in the documentation it says to run the commands in the following format: 

|script python tanium_nlp ....

If you install the app from Github and not Splunkbase, you can run the app by simply using the aliases script name as above. 

| taniumnlp ..........

**Comment by JCobeyTanium** [comment]
Removing all inline searching
